SHREYOSHI GHOSH Machine Learning and Data Science for Bioinformatics HOMEWORK 1

1. 
Testing Pandas. Install pandas (if not present in your environment). Attempt the following
subtasks after installation.
a. Create a sample Data Frame with 4 columns and 8 rows.
b. Print the shape, type and column names of the corresponding Dataframe.

In [1]:
import numpy as np 
import pandas as pd 
data = {'col1': np.random.randint(0,100,size=8), 'col2': np.random.randint(0,100,size=8),'col3': np.random.randint(0,100,size=8),'col4': np.random.randint(0,100,size=8)}
sample_df = pd.DataFrame(data = data)
sample_df

col1  col2  col3  col4
0    68    82    33    84
1    47    40    28    46
2    72    71    45    27
3    35    91    20    49
4    84    84    68    89
5    42    54    67    25
6    97     3    76     3
7    72    79    87    15

In [2]:
sample_df.shape

(8, 4)

In [3]:
sample_df.dtypes

col1    int64
col2    int64
col3    int64
col4    int64
dtype: object

In [4]:
sample_df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

2. 
Testing Numpy. Install numpy (if not present in your environment). Attempt the following
subtasks after installation.
a. Create a sample numpy array of random integers with 6 rows and 6 columns.
b. Print the shape, dimensions of the array
c. Print the elements greater than the element at index (3, 3)

In [5]:
arr = np.array([np.random.randint(0,100,size=6), 
                np.random.randint(0,100,size=6),
                np.random.randint(0,100,size=6), 
                np.random.randint(0,100,size=6), 
                np.random.randint(0,100,size=6), 
                np.random.randint(0,100,size=6), ])
arr

array([[18, 30,  0, 83, 10, 56],
       [58, 52, 24, 21,  2, 50],
       [14, 38, 68, 45, 42, 12],
       [ 1, 74, 70, 17, 40, 46],
       [21, 16, 22, 54, 76,  2],
       [38, 73, 72, 43,  3,  4]])

In [6]:
arr.shape

(6, 6)

In [7]:
arr[3:,3:]

array([[17, 40, 46],
       [54, 76,  2],
       [43,  3,  4]])

3. 
Familiarize yourself with Scikit-Learn. In this task you will use the sklearn library to implement a Decision tree on iris dataset, available in the sklearn library. Use the sklearn in-built Decision tree model. Finally, print its confusion matrix and classification report.

In [8]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix



iris = datasets.load_iris()
x = iris.data
y = iris.target

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state = 50, test_size = 0.25)

tree = DecisionTreeClassifier()
tree.fit(x_train,y_train)
y_pred = tree.predict(x_test)


In [9]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      0.93      0.93        15
           2       0.92      0.92      0.92        12

    accuracy                           0.95        38
   macro avg       0.95      0.95      0.95        38
weighted avg       0.95      0.95      0.95        38



In [10]:
print(confusion_matrix(y_test, y_pred))

[[11  0  0]
 [ 0 14  1]
 [ 0  1 11]]
